// masterWrestlerDatabase.js
// Exports the master wrestler database as an array of objects: { name }

const masterWrestlerDatabase = [
   { name: 'Abdullah the Butcher' },
    { name: 'Abyss' },
    { name: 'Adam Cole' },
    { name: 'Adam Page' },
    { name: 'Afa' },
    { name: 'AJ Styles' },
    { name: 'Akira Taue' },
    { name: 'Al Snow' },
    { name: 'Alberto Del Rio' },
    { name: 'Andre the Giant' },
    { name: 'Animal (Road Warrior)' },
    { name: 'Antonio Inoki' },
    { name: 'Arn Anderson' },
    { name: 'Bad News Brown' },
    { name: 'Bam Bam Bigelow' },
    { name: 'Baron Von Raschke' },
    { name: 'Barry Windham' },
    { name: 'Batista' },
    { name: 'Big Boss Man' },
    { name: 'Big E' },
    { name: 'Big Show' },
    { name: 'Billy Graham' },
    { name: 'Billy Gunn' },
    { name: 'Blackjack Mulligan' },
    { name: 'Blue Demon' },
    { name: 'Bob Armstrong' },
    { name: 'Bob Backlund' },
    { name: 'Bobo Brazil' },
    { name: 'Bobby Eaton' },
    { name: 'Bobby Fish' },
    { name: 'Bobby Lashley' },
    { name: 'Bobby Roode' },
    { name: 'Booker T' },
    { name: 'Braun Strowman' },
    { name: 'Bret Hart' },
    { name: 'Brian Pillman' },
    { name: 'Brock Lesnar' },
    { name: 'Brodie Lee' },
    { name: 'Bron Breakker' },
    { name: 'Bronco Nagurski' },
    { name: 'Bruiser Brody' },
    { name: 'Bruno Sammartino' },
    { name: 'Brutus Beefcake' },
    { name: 'Bubba Ray Dudley' },
    { name:'Buddy Rogers' },
    { name: 'Bull Curry' },
    { name: 'Captain Lou Albano' },
    { name: 'Cesaro' },
    { name: 'Chad Gable' },
    { name: 'Chris Adams' },
    { name: 'Chris Benoit' },
    { name: 'Chris Candido' },
    { name: 'Chris Daniels' },
    { name: 'Chris Hero' },
    { name: 'Chris Jericho' },
    { name: 'Chris Sabin' },
    { name: 'Christian Cage' },
    { name: 'CM Punk' },
    { name: 'Cody Rhodes' },
    { name: 'Crusher' },
    { name: 'D-Von Dudley' },
    { name: 'Damian Priest' },
    { name: 'Daniel Bryan' },
    { name: 'Danny Hodge' },
    { name: 'Davey Boy Smith' },
    { name: 'David Von Erich' },
    { name: 'Dean Malenko' },
    { name: 'Diamond Dallas Page' },
    { name: 'Dick Beyer (The Destroyer)' },
    { name: 'Dick Murdoch' },
    { name: 'Dick the Bruiser' },
    { name: 'DLo Brown' },
    { name: 'Dolph Ziggler' },
    { name: 'Dominic DeNucci' },
    { name: 'Dominik Mysterio' },
    { name: 'Don Muraco' },
    { name: 'Dory Funk Jr.' },
    { name: 'Dr. Death Steve Williams' },
    { name: 'Dr. Wagner Jr.' },
    { name: 'Drew McIntyre' },
    { name: 'Dusty Rhodes' },
    { name: 'Dynamite Kid' },
    { name: 'Earthquake' },
    { name: 'Eddie Gilbert' },
    { name: 'Eddie Guerrero' },
    { name: 'Eddie Kingston' },
    { name: 'Edge' },
    { name: 'El Canek' },
    { name: 'El Hijo del Santo' },
    { name: 'El Santo' },
    { name: 'Eric Young' },
    { name: 'Ernie Ladd' },
    { name: 'Finn Bálor' },
    { name: 'Fit Finlay' },
    { name: 'Fritz Von Erich' },
    { name: 'Gene Kiniski' },
    { name: 'Genichiro Tenryu' },
    { name: 'George Hackenschmidt' },
    { name: 'George Steele' },
    { name: 'Giant Baba' },
    { name: 'Goldberg' },
    { name: 'Goldust' },
    { name: 'Gorilla Monsoon' },
    { name: 'Gorgeous George' },
    { name: 'Great Muta' },
    { name: 'Great Sasuke' },
    { name: 'Greg Valentine' },
    { name: 'Gunther' },
    { name: 'Haku' },
    { name: 'Harley Race' },
    { name: 'Hawk (Road Warrior)' },
    { name: 'Hayabusa' },
    { name: 'Hiroshi Tanahashi' },
    { name: 'Honky Tonk Man' },
    { name: 'Hulk Hogan' },
    { name: 'Ilja Dragunov' },
    { name: 'Ivan Koloff' },
    { name: 'Ivan Putski' },
    { name: 'Jack Brisco' },
    { name: 'Jake Roberts' },
    { name: 'Jay Briscoe' },
    { name: 'Jay Lethal' },
    { name: 'Jay White' },
    { name: 'JBL' },
    { name: 'Jeff Cobb' },
    { name: 'Jeff Hardy' },
    { name: 'Jeff Jarrett' },
    { name: 'Jerry Brisco' },
    { name: 'Jerry Lawler' },
    { name: 'Jerry Lynn' },
    { name: 'Jey Uso' },
    { name: 'Jim Duggan' },
    { name: 'Jim Londos' },
    { name: 'Jim Neidhart' },
    { name: 'Jimmy Snuka' },
    { name: 'Jimmy Uso' },
    { name: 'John Cena' },
    { name: 'John Kronus' },
    { name: 'John Morrison' },
    { name: 'Johnny Gargano' },
    { name: 'Johnny Valentine' },
    { name: 'Jon Moxley' },
    { name: 'Jun Akiyama' },
    { name: 'Junkyard Dog' },
    { name: 'Jushin Thunder Liger' },
    { name: 'Kane' },
    { name: 'Karl Anderson' },
    { name: 'Karl Gotch' },
    { name: 'Karrion Kross' },
    { name: 'Kazuchika Okada' },
    { name: 'Ken Shamrock' },
    { name: 'Kendo Nagasaki' },
    { name: 'Kenny Omega' },
    { name: 'Kenta' },
    { name: 'Kenta Kobashi' },
    { name: 'Kerry Von Erich' },
    { name: 'Kevin Nash' },
    { name: 'Kevin Owens' },
    { name: 'Kevin Sullivan' },
    { name: 'Kevin Von Erich' },
    { name: 'Killer Khan' },
    { name: 'Killer Kowalski' },
    { name: 'King Curtis Iaukea' },
    { name: 'King Kong Bundy' },
    { name: 'Kofi Kingston' },
    { name: 'Koko B. Ware' },
    { name: 'Konnan' },
    { name: 'Kurt Angle' },
    { name: 'KUSHIDA' },
    { name: 'LA Knight' },
    { name: 'Lance Storm' },
    { name: 'Larry Zbyszko' },
    { name: 'Lex Luger' },
    { name: 'Lou Thesz' },
    { name: 'Low Ki' },
    { name: 'Luke Gallows' },
    { name: 'Magnum T.A.' },
    { name: 'Mark Briscoe' },
    { name: 'Mark Henry' },
    { name: 'Marty Jannetty' },
    { name: 'Masahiro Chono' },
    { name: 'Masato Tanaka' },
    { name: 'Matt Hardy' },
    { name: 'Matt Jackson' },
    { name: 'Michael Hayes' },
    { name: 'Mick Foley' },
    { name: 'Mike Awesome' },
    { name: 'Mike Rotunda' },
    { name: 'Mil Mascaras' },
    { name: 'Minoru Suzuki' },
    { name: 'Mitsuharu Misawa' },
    { name: 'The Miz' },
    { name: 'MJF' },
    { name: 'Mr. Fuji' },
    { name: 'Mr. Perfect' },
    { name: 'Mr. Wrestling II' },
    { name: 'Muhammad Ali' },
    { name: 'Naomichi Marufuji' },
    { name: 'New Jack' },
    { name: 'Nick Aldis' },
    { name: 'Nick Bockwinkel' },
    { name: 'Nick Gage' },
    { name: 'Nick Jackson' },
    { name: 'Nikolai Volkoff' },
    { name: 'Ole Anderson' },
    { name: 'One Man Gang' },
    { name: 'Owen Hart' },
    { name: 'PAC' },
    { name: 'Pat OConnor' },
    { name: 'Pat Patterson' },
    { name: 'Paul Orndorff' },
    { name: 'Pentagon Jr.' },
    { name: 'Perry Saturn' },
    { name: 'Pete Dunne' },
    { name: 'Psicosis' },
    { name: 'Psycho Sid' },
    { name: 'R-Truth' },
    { name: 'Randy Orton' },
    { name: 'Randy Savage' },
    { name: 'Raven' },
    { name: 'Rey Fenix' },
    { name: 'Rey Mysterio' },
    { name: 'Ric Flair' },
    { name: 'Ricochet' },
    { name: 'Rick Rude' },
    { name: 'Rick Steiner' },
    { name: 'Ricky Steamboat' },
    { name: 'Rikidozan' },
    { name: 'Rikishi' },
    { name: 'Riki Choshu' },
    { name: 'Road Dogg' },
    { name: 'Rob Van Dam' },
    { name: 'The Rock' },
    { name: 'Rocky Johnson' },
    { name: 'Roddy Piper' },
    { name: 'Roman Reigns' },
    { name: 'Ron Fuller' },
    { name: 'Ron Simmons' },
    { name: 'Sabu' },
    { name: 'Samoa Joe' },
    { name: 'Sami Zayn' },
    { name: 'Sammy Guevara' },
    { name: 'Sandman' },
    { name: 'Scott Hall' },
    { name: 'Scott Steiner' },
    { name: 'Sgt. Slaughter' },
    { name: 'Seth Rollins' },
    { name: 'Shane Douglas' },
    { name: 'Shane McMahon' },
    { name: 'Shawn Michaels' },
    { name: 'Sheamus' },
    { name: 'Shelton Benjamin' },
    { name: 'Shingo Takagi' },
    { name: 'Shinsuke Nakamura' },
    { name: 'Sika' },
    { name: 'Stan Hansen' },
    { name: 'Stan Stasiak' },
    { name: 'Steve Corino' },
    { name: 'Sting' },
    { name: 'Stone Cold Steve Austin' },
    { name: 'Stu Hart' },
    { name: 'Zack Sabre Jr.' },
    { name: 'Superstar Billy Graham' },
    { name: 'Tajiri' },
    { name: 'Tatanka' },
    { name: 'Tatsumi Fujinami' },
    { name: 'Tazz' },
    { name: 'Ted DiBiase' },
    { name: 'Terry Funk' },
    { name: 'Terry Gordy' },
    { name: 'Tetsuya Naito' },
    { name: 'The Barbarian' },
    { name: 'The Great Khali' },
    { name: 'The Sheik' },
    { name: 'The Undertaker' },
    { name: 'Tiger Mask' },
    { name: 'Tito Santana' },
    { name: 'Tommaso Ciampa' },
    { name: 'Tommy Dreamer' },
    { name: 'Tommy Rich' },
    { name: 'Tony Atlas' },
    { name: 'Toshiaki Kawada' },
    { name: 'Triple H' },
    { name: 'Tully Blanchard' },
    { name: 'Typhoon' },
    { name: 'Vader' },
    { name: 'Ultimo Dragon' },
    { name: 'Umaga' },
    { name: 'Ultimate Warrior' },
    { name: 'Vader' },
    { name: 'Vampiro' },
    { name: 'Verne Gagne' },
    { name: 'Vince McMahon' },
    { name: 'Wahoo McDaniel' },
    { name: 'Wardlow' },
    { name: 'William Regal' },
    { name: 'Will Ospreay' },
    { name: 'X-Pac' },
    { name: 'Yokozuna' },
    { name: 'Yoshihiro Takayama' },
    { name: 'Yuji Nagata' },
    { name: 'Zack Sabre Jr.' }
];

// For browser usage:
if (typeof window !== 'undefined') {
    window.masterWrestlerDatabase = masterWrestlerDatabase;
}

// For module usage:
if (typeof module !== 'undefined') {
    module.exports = masterWrestlerDatabase;
}
